version: "3.1"

networks:
  internal:
  traefik_default:
    external: true

services:

  backend:
    image: docker.io/postgres:13
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - internal
    container_name: taskmaster-db
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-external-labels: job=docker,container_name={{.Name}},owner=curiosdevcookie,environment=development
    hostname: backend

  frontend:
    image: ghcr.io/curiosdevcookie/taskmaster-app:latest
    env_file: .env
    environment:
      PHX_CHECK_ORIGIN: https://$PHX_HOST
      POOL_SIZE: 10
      PORT: 8080
    networks:
      - traefik_default
      - internal
    container_name: taskmaster
    volumes:
      - app_data:/app/priv/static/uploads
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-external-labels: job=docker,container_name={{.Name}},owner=curiosdevcookie,environment=development
    depends_on:  
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.services.taskmaster-studio.loadbalancer.server.port=8080"
      - "traefik.http.routers.taskmaster-studio.rule=Host(`test.taskmaster.studio`)"
      - "traefik.http.routers.taskmaster-studio.entrypoints=websecure"
      - "traefik.http.routers.taskmaster-studio.tls=true"
      - "traefik.http.routers.taskmaster-studio.tls.certresolver=leresolver"
  migration:
    image: ghcr.io/curiosdevcookie/taskmaster-app:latest
    depends_on:
      backend:
        condition: service_healthy
    command: ["mix", "ecto.migrate"]
    env_file:
      - .env
    container_name: taskmaster-migration
    networks:
      - internal
volumes:
  db_data:
  app_data:
