name: Deploy to Dev

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 24 ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
      - name: Prepare Deployment
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.ARTIFACT_USER }}@${{ secrets.ARTIFACT_HOST }} 'bash -s' < .github/scripts/deploy_dev.sh
          mkdir -p tmp
          sed 's/🙂docker_image🙃/ghcr.io/${{ github.repository }}-app:${{ github.sha }}/g' docker-compose.yml > tmp/docker-compose.yml
          scp -P 24 tmp/docker-compose.yml ${{ secrets.ARTIFACT_USER }}@${{ secrets.ARTIFACT_HOST }}:/home/${{ secrets.ARTIFACT_USER }}/docker-compose.yml
